script: gray_dualchan_pretrain_mu.py
log_name: DAWN_gray
noise_type: CT_data
log_dir: ckpt
trainset: SMF0723_don_15040001,SMF0723_acc_15040001
valset: SMF0723_don_1504val,SMF0723_acc_1504val
input_channel: 3
output_channel: 1
middle_channel: 96
blindspot_conv_type: Mask3D
blindspot_conv_bias: true
br1_block_num: 8
br1_blindspot_conv_ks: 3
br2_block_num: 8
br2_blindspot_conv_ks: 5
activate_fun: Relu
patch_size: 96
batch_size: 8
load_thread: 4
epoch: 40
steps: "30,60,80"
loss_choice: L2_video
weight: One
lr_dbsn: 0.0003
decay_rate: 0.1
resume: new
last_ckpt: ""
CT_data_description: ""
bsn_ver: dbsn_fuse
mask_shape: o
device_ids: all
dynamic_load: True
no_flip: false
frame_shuffle: false
unet_skip: True
data_rate: 1.0
repeat: 1
extra_args: ""
